<%@page contentType="text/html" pageEncoding="utf-8"%>
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />  
  <title>GMS World - Device Locator Commands</title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0" /> 
  <link rel="stylesheet" media="all" href="/style.css" type="text/css">
  <%@ include file="/WEB-INF/jspf/head_small.jspf" %>
</head>

<body>
 <div class="wrap">
    <%@ include file="/WEB-INF/jspf/header_mobile.jspf" %>
       
    <div class="content">
    	<article>
    	
    	<h3>Device locator sms commands</h3>
    	
    	In order to execute remotely command on Device Locator you need to send SMS message with following structure: 
    	
    	<p><b>&lt;command&gt;&lt;security pin&gt; &lt;optional parameters&gt;</b></p>
    	
    	<b>Security PIN</b> is generated by Device Locator at first startup and you can find it and change it on Device Locator main screen. <br/><br/>
    	
    	Following <b>Commands</b> are available in Device Locator:
    	
    	<ul>
    	   <li><b>Locatedl</b> - share current device location<br/>Usage: Locatedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Locatedl1234</b><br/></li>
    	   <li><b>Startdl</b> - start device location tracking and start/continue location recoding<br/>Usage: Startdl&lt;security pin&gt;.<br/>Example (assuming your security pin is 1234): <b>Startdl1234</b><br/></li>
           <li><b>Stopdl</b> - stop device location tracking <br/>Usage: Stopdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Stopdl1234</b><br/></li>
           <li><b>Resetdl</b> - start device location tracking and start/reset location recoding<br/>Usage: Resetdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Resetdl1234</b><br/></li>
           <li><b>Routedl</b> - send currently recorded locations route to the GMS World. In response you'll receive link to your route map web page<br/>Usage: Routedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Routedl1234</b><br/></li> 
           <li><b>Gpshighdl</b> - set high GPS accuracy for device location tracking service (this will faster consume device battery)<br/>Usage: Gpshighdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Gpshighdl1234</b><br/></li>
           <li><b>Gpsbalancedl</b> - set balanced GSP accuracy for device location tracking service (this will slower consume device battery)<br/>Usage: Gpsbalanceddl&lt;security pin&gt;. <br/>Example (assuming your security pin is 1234): <b>Gpsbalancedl1234</b><br/></li>
           <li><b>Radiusdl</b> - change device tracking service radius in meters. Every time when device will move outside the radius you'll be notified<br/>Usage: Radiusdl&lt;security pin&gt; x  where x is number of meters &gt; 0. <br/>Example (assuming your security pin is 1234, and radius is 500 meters): <b>Radiusdl1234 500</b><br/></li>
           <li><b>Mutedl</b> - mute device audio<br/>Usage: Mutedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Mutedl1234</b><br/></li>
           <li><b>Normaldl</b> - restore normal device audio setting (turn off  mute)<br/>Usage: Normaldl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Normaldl1234</b><br/></li>
           <li><b>Calldl</b> -  call sender. Device should initiate phone call to you<br/>Usage: Calldl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Calldl1234</b><br/></li>
    	</ul> 
       
    	</article>
    	
    	<%@ include file="/WEB-INF/jspf/ad_small_baner.jspf" %>
    </div>
    <%@ include file="/WEB-INF/jspf/footer_mobile.jspf" %>
  </div>
 
  <script src="/js/jquery.min.js"></script>
  <script type="text/javascript">
    window.addEventListener("load",function() {
	  // Set a timeout...
	  setTimeout(function(){
	    // Hide the address bar!
	    window.scrollTo(0, 1);
	  }, 0);
	});
    $('.search-box,.menu' ).hide();   
    $('.options li:first-child').click(function(){	
   		$(this).toggleClass('active'); 	
   		$('.search-box').toggle();        			
   		$('.menu').hide();  		
   		$('.options li:last-child').removeClass('active'); 
    });
    $('.options li:last-child').click(function(){
   		$(this).toggleClass('active');      			
   		$('.menu').toggle();  		
   		$('.search-box').hide(); 
   		$('.options li:first-child').removeClass('active'); 		
    });
    $('.content').click(function(){
   		$('.search-box,.menu' ).hide();   
   		$('.options li:last-child, .options li:first-child').removeClass('active');
    });
  </script>
</body>

</html>
