<%@page contentType="text/html" pageEncoding="utf-8"%>
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />  
  <title>GMS World - Device Locator Commands</title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0" /> 
  <link rel="stylesheet" media="all" href="/style.css" type="text/css">
  <%@ include file="/WEB-INF/jspf/head_small.jspf" %>
</head>

<body>
 <div class="wrap">
    <%@ include file="/WEB-INF/jspf/header_mobile.jspf" %>
       
    <div class="content">
    	<article>
    	
    	<h3>Device Locator  commands</h3>
    	
    	In order to get some commands to work on your device you'll need to grant number of permissions in the application.
    	Starting from Device Locator 0.4 in addition to SMS commands you can send cloud commands directly from Device Locator to other device with Device Locator installed using our cloud messaging system.  
    	In order to execute command on remote device with Device Locator installed you need to send following SMS or cloud message: 
    	
    	<p><b>&lt;command&gt;&lt;security pin&gt; &lt;optional parameters&gt;</b></p>
    	
    	<b>Security PIN</b> is generated by Device Locator during application installation and you can find it and change it at any time on Security PIN card. Security PIN must be at least 4 digits. <font color="red">Remember to protect your PIN!</font><br/><br/>
    	
    	<b>Commands</b> available in Device Locator:
    	
    	<ul>
    	   <li><a id="locate"><b>Locate</b></a> - send current device GPS location. Requires Location permission granted.<br/>Usage: Locatedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Locatedl1234</b><br/></li>
    	   <li><a id="hello"><b>Hello</b></a> - send hello message to check connectivity with the device. Requires Device Locator version 0.4-22. For previous versions use Ping instead of Hello.<br/>Usage: Hellodl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Hellodl1234</b><br/></li>  
    	   <li><a id="ring"><b>Ring</b></a> - start playing ring tone on the device. If your ring tone is stored on device storage requires Storage permission granted. <font color="red">You can send this command again to stop playing ring tone.</font><br/>Usage: Ringdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Ringdl1234</b><br/></li>  
           <li><a id="call"><b>Call</b></a> -  call sender. Device should initiate phone call to SMS sender number or number specified as command parameter. Requires Phone permission granted.<br/>Usage: Calldl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Calldl1234</b><br/></li>
    	   <li><a id="photo"><b>Photo</b></a> -  take photo with front camera. You'll receive link to photo image. Requires enabled failed login service and granted Camera permission.<br/>Usage: Photodl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Photodl1234</b><br/></li>
    	   <li><a id="lock"><b>Lock</b></a> -  lock device screen. Requires Lock Screen permission granted.<br/>Usage: Lockdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Lockdl1234</b><br/></li>
    	   <li><a id="reset"><b>Reset</b></a> - reset device to factory defaults and wipe all data and applications. Requires Device Reset permission granted.<br/>Usage:Resetdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Resetdl1234</b><br/></li>
           <li><a id="start"><b>Start</b></a> - start device location tracking and location recoding. Requires Location permission granted.<br/>Usage: Startdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Startdl1234</b><br/></li>
           <li><a id="stop"><b>Stop</b></a> - stop device location tracking.<br/>Usage: Stopdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Stopdl1234</b><br/></li>
           <li><a id="resume"><b>Resume</b></a> - resume or start device location tracking and location recoding. Requires Location permission granted.<br/>Usage: Resumedl&lt;security pin&gt;.<br/>Example (assuming your security pin is 1234): <b>Resumedl1234</b><br/></li>
           <li><a id="route"><b>Route</b></a> - save currently recorded locations route to our backend. You'll receive link to route map.<br/>Usage: Routedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Routedl1234</b><br/></li> 
           <li><a id="radius"><b>Radius</b></a> - change device tracking service radius in meters. Every time device will move outside the area within the radius you'll be notified according to your Notification settings.<br/>Usage: Radiusdl&lt;security pin&gt; x  where x is number of meters &gt; 0. <br/>Example (assuming your security pin is 1234, and radius is 500 meters): <b>Radiusdl1234 500</b><br/></li>
           <li><a id="mute"><b>Mute</b></a> - mute device audio. Requires Don't Disturb permission on some devices with Android 6+<br/>Usage: Mutedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Mutedl1234</b><br/></li>
           <li><a id="unmute"><b>Unmute</b></a> - unmute device audio.<br/>Usage: Unmutedl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Unmutedl1234</b><br/></li>
           <li><a id="notify"><b>Nofity</b></a> - set or change who should be notified by location tracking service.<br/>Usage: Notifydl&lt;security pin&gt; x  where x is p:y for phone number, m:y for email address or t:y for Telegram chat id. You could set all parameters separately or together. Email address and Telegram chat id are subject for validation by it's owners.<br/>Example (assuming your security pin is 1234, phone number is 123456789, email address is name@domain.com and Telegram chat id is 987654321): <b>Notifydl1234 p:123456789 m:name@domain.com t:987654321</b><br/></li>
           <li><a id="config"><b>Config</b></a> - change some Device Locator configuration.<br/>Usage: Configdl&lt;security pin&gt; x  where x can be any of: <b>lm:on</b> to enable Acknowledge Location notification message, <b>lm:off</b> to disable Acknowledge Location notification message, <b>gpsm:on</b> to enable GPS Location notification message, <b>gpsm:off</b> to disable GPS Location notification message, <b>mapm:on</b> to enable Map link Location notification message, <b>mapm:off</b> to disable Map link Location notification message, 
           <b>gpsb:on</b> and <b>gpsh:off</b> to set balanced GPS accuracy for device location tracking service, <b>gpsh:on</b> and <b>gpsb:off</b> to set high GPS accuracy for device location tracking service, <b>nt:on</b> to send test notification to registered notifiers. You could set all parameters separately or together. <br/>Example (assuming your security pin is 1234, and you want to enable Acknowledge Location messages and Map link Location notification message): <b>Configdl1234 lm:on mapm:on</b><br/></li>
           <li><a id="about"><b>About</b></a> - send Device Locator version information.<br/>Usage: Aboutdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Aboutdl1234</b><br/></li>  
    	   <!--li><a id="gpshigh"><b>Gpshigh</b></a> - Deprecated: use Configdl gpsh:on. Set high GPS accuracy for device location tracking service (this will consume faster device battery, and location will be more accurate).<br/>Usage: Gpshighdl&lt;security pin&gt;<br/>Example (assuming your security pin is 1234): <b>Gpshighdl1234</b><br/></li>
           <li><a id="gpsbalance"><b>Gpsbalance</b></a> - Deprecated: use Configdl gpsb:on. Set balanced GPS accuracy for device location tracking service (this will consume slower device battery and location will be less accurate).<br/>Usage: Gpsbalanceddl&lt;security pin&gt;. <br/>Example (assuming your security pin is 1234): <b>Gpsbalancedl1234</b><br/></li-->
    	</ul> 
       
    	</article>
    	
    	<%@ include file="/WEB-INF/jspf/ad_small_baner.jspf" %>
    </div>
    <%@ include file="/WEB-INF/jspf/footer_mobile.jspf" %>
  </div>
 
  <script src="/js/jquery.min.js"></script>
  <script type="text/javascript">
    window.addEventListener("load",function() {
	  // Set a timeout...
	  setTimeout(function(){
	    // Hide the address bar!
	    window.scrollTo(0, 1);
	  }, 0);
	});
    $('.search-box,.menu' ).hide();   
    $('.options li:first-child').click(function(){	
   		$(this).toggleClass('active'); 	
   		$('.search-box').toggle();        			
   		$('.menu').hide();  		
   		$('.options li:last-child').removeClass('active'); 
    });
    $('.options li:last-child').click(function(){
   		$(this).toggleClass('active');      			
   		$('.menu').toggle();  		
   		$('.search-box').hide(); 
   		$('.options li:first-child').removeClass('active'); 		
    });
    $('.content').click(function(){
   		$('.search-box,.menu' ).hide();   
   		$('.options li:last-child, .options li:first-child').removeClass('active');
    });
  </script>
</body>

</html>
